// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cabins.sql

package db

import (
	"context"
)

const cabinExists = `-- name: CabinExists :one
SELECT EXISTS(SELECT 1 FROM cabins WHERE id = $1)
`

func (q *Queries) CabinExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, cabinExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const claimCabin = `-- name: ClaimCabin :execrows
UPDATE cabins
SET owner_user_id = $2
WHERE id = $1 AND (owner_user_id IS NULL OR owner_user_id = $2)
`

type ClaimCabinParams struct {
	ID          string `json:"id"`
	OwnerUserID *int64 `json:"owner_user_id"`
}

func (q *Queries) ClaimCabin(ctx context.Context, arg ClaimCabinParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimCabin, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCabin = `-- name: CreateCabin :one
INSERT INTO cabins (id, owner_user_id, name)
VALUES ($1, $2, $3)
RETURNING id, owner_user_id, name, online, last_seen, created_at
`

type CreateCabinParams struct {
	ID          string `json:"id"`
	OwnerUserID *int64 `json:"owner_user_id"`
	Name        string `json:"name"`
}

func (q *Queries) CreateCabin(ctx context.Context, arg CreateCabinParams) (Cabin, error) {
	row := q.db.QueryRow(ctx, createCabin, arg.ID, arg.OwnerUserID, arg.Name)
	var i Cabin
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Online,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCabinsByOwner = `-- name: DeleteCabinsByOwner :execrows
DELETE FROM cabins WHERE owner_user_id = $1
`

func (q *Queries) DeleteCabinsByOwner(ctx context.Context, ownerUserID *int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCabinsByOwner, ownerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCabin = `-- name: GetCabin :one
SELECT id, owner_user_id, name, online, last_seen, created_at
FROM cabins WHERE id = $1
`

func (q *Queries) GetCabin(ctx context.Context, id string) (Cabin, error) {
	row := q.db.QueryRow(ctx, getCabin, id)
	var i Cabin
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Online,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const getCabinConfig = `-- name: GetCabinConfig :one
SELECT cabin_id, thresholds, decision, updated_at
FROM cabin_config WHERE cabin_id = $1
`

func (q *Queries) GetCabinConfig(ctx context.Context, cabinID string) (CabinConfig, error) {
	row := q.db.QueryRow(ctx, getCabinConfig, cabinID)
	var i CabinConfig
	err := row.Scan(
		&i.CabinID,
		&i.Thresholds,
		&i.Decision,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCabinConfig = `-- name: InsertCabinConfig :exec
INSERT INTO cabin_config (cabin_id, thresholds, decision)
VALUES ($1, $2, $3)
`

type InsertCabinConfigParams struct {
	CabinID    string `json:"cabin_id"`
	Thresholds []byte `json:"thresholds"`
	Decision   []byte `json:"decision"`
}

func (q *Queries) InsertCabinConfig(ctx context.Context, arg InsertCabinConfigParams) error {
	_, err := q.db.Exec(ctx, insertCabinConfig, arg.CabinID, arg.Thresholds, arg.Decision)
	return err
}

const listActuatorStates = `-- name: ListActuatorStates :many
SELECT cabin_id, actuator, state, speed, source, updated_at
FROM actuator_state WHERE cabin_id = $1
`

func (q *Queries) ListActuatorStates(ctx context.Context, cabinID string) ([]ActuatorState, error) {
	rows, err := q.db.Query(ctx, listActuatorStates, cabinID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActuatorState
	for rows.Next() {
		var i ActuatorState
		if err := rows.Scan(
			&i.CabinID,
			&i.Actuator,
			&i.State,
			&i.Speed,
			&i.Source,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCabinsByOwner = `-- name: ListCabinsByOwner :many
SELECT id, owner_user_id, name, online, last_seen, created_at
FROM cabins WHERE owner_user_id = $1
ORDER BY created_at
`

func (q *Queries) ListCabinsByOwner(ctx context.Context, ownerUserID *int64) ([]Cabin, error) {
	rows, err := q.db.Query(ctx, listCabinsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cabin
	for rows.Next() {
		var i Cabin
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Online,
			&i.LastSeen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCabinConfig = `-- name: UpdateCabinConfig :exec
UPDATE cabin_config
SET thresholds = $2, decision = $3, updated_at = now()
WHERE cabin_id = $1
`

type UpdateCabinConfigParams struct {
	CabinID    string `json:"cabin_id"`
	Thresholds []byte `json:"thresholds"`
	Decision   []byte `json:"decision"`
}

func (q *Queries) UpdateCabinConfig(ctx context.Context, arg UpdateCabinConfigParams) error {
	_, err := q.db.Exec(ctx, updateCabinConfig, arg.CabinID, arg.Thresholds, arg.Decision)
	return err
}
