// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type ActuatorState struct {
	CabinID   string    `json:"cabin_id"`
	Actuator  string    `json:"actuator"`
	State     bool      `json:"state"`
	Speed     int32     `json:"speed"`
	Source    string    `json:"source"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Alert struct {
	ID      int64     `json:"id"`
	CabinID string    `json:"cabin_id"`
	Ts      time.Time `json:"ts"`
	Type    string    `json:"type"`
	Message string    `json:"message"`
}

type Cabin struct {
	ID          string     `json:"id"`
	OwnerUserID *int64     `json:"owner_user_id"`
	Name        string     `json:"name"`
	Online      bool       `json:"online"`
	LastSeen    *time.Time `json:"last_seen"`
	CreatedAt   time.Time  `json:"created_at"`
}

type CabinConfig struct {
	CabinID    string    `json:"cabin_id"`
	Thresholds []byte    `json:"thresholds"`
	Decision   []byte    `json:"decision"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Reading struct {
	ID          int64     `json:"id"`
	CabinID     string    `json:"cabin_id"`
	Ts          time.Time `json:"ts"`
	Temperature *float64  `json:"temperature"`
	Humidity    *float64  `json:"humidity"`
	Tds         *float64  `json:"tds"`
	Ph          *float64  `json:"ph"`
	ShtOk       bool      `json:"sht_ok"`
	RtcOk       bool      `json:"rtc_ok"`
	TdsOk       bool      `json:"tds_ok"`
	PhOk        bool      `json:"ph_ok"`
}

type User struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
