// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	CabinExists(ctx context.Context, id string) (bool, error)
	ClaimCabin(ctx context.Context, arg ClaimCabinParams) (int64, error)
	CreateCabin(ctx context.Context, arg CreateCabinParams) (Cabin, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCabinsByOwner(ctx context.Context, ownerUserID *int64) (int64, error)
	DeleteReadingsOlderThan(ctx context.Context, ts time.Time) (int64, error)
	DeleteUser(ctx context.Context, id int64) (int64, error)
	EnsureCabin(ctx context.Context, id string) error
	EnsureCabinConfig(ctx context.Context, arg EnsureCabinConfigParams) error
	GetCabin(ctx context.Context, id string) (Cabin, error)
	GetCabinConfig(ctx context.Context, cabinID string) (CabinConfig, error)
	GetLatestReading(ctx context.Context, cabinID string) (GetLatestReadingRow, error)
	GetReadings(ctx context.Context, arg GetReadingsParams) ([]GetReadingsRow, error)
	GetReadingsHourly(ctx context.Context, arg GetReadingsHourlyParams) ([]GetReadingsHourlyRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	InsertAlert(ctx context.Context, arg InsertAlertParams) error
	InsertCabinConfig(ctx context.Context, arg InsertCabinConfigParams) error
	InsertReading(ctx context.Context, arg InsertReadingParams) error
	ListActuatorStates(ctx context.Context, cabinID string) ([]ActuatorState, error)
	ListCabinsByOwner(ctx context.Context, ownerUserID *int64) ([]Cabin, error)
	MarkCabinOffline(ctx context.Context, id string) error
	MarkCabinOnline(ctx context.Context, arg MarkCabinOnlineParams) error
	UpdateCabinConfig(ctx context.Context, arg UpdateCabinConfigParams) error
	UpsertActuatorState(ctx context.Context, arg UpsertActuatorStateParams) error
}

var _ Querier = (*Queries)(nil)
