// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telemetry.sql

package db

import (
	"context"
	"time"
)

const deleteReadingsOlderThan = `-- name: DeleteReadingsOlderThan :execrows
DELETE FROM readings WHERE ts < $1
`

func (q *Queries) DeleteReadingsOlderThan(ctx context.Context, ts time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReadingsOlderThan, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureCabin = `-- name: EnsureCabin :exec
INSERT INTO cabins (id) VALUES ($1)
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) EnsureCabin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, ensureCabin, id)
	return err
}

const ensureCabinConfig = `-- name: EnsureCabinConfig :exec
INSERT INTO cabin_config (cabin_id, thresholds, decision)
VALUES ($1, $2, $3)
ON CONFLICT (cabin_id) DO NOTHING
`

type EnsureCabinConfigParams struct {
	CabinID    string `json:"cabin_id"`
	Thresholds []byte `json:"thresholds"`
	Decision   []byte `json:"decision"`
}

func (q *Queries) EnsureCabinConfig(ctx context.Context, arg EnsureCabinConfigParams) error {
	_, err := q.db.Exec(ctx, ensureCabinConfig, arg.CabinID, arg.Thresholds, arg.Decision)
	return err
}

const getLatestReading = `-- name: GetLatestReading :one
SELECT cabin_id, ts, temperature, humidity, tds, ph, sht_ok, rtc_ok, tds_ok, ph_ok
FROM readings
WHERE cabin_id = $1
ORDER BY ts DESC
LIMIT 1
`

type GetLatestReadingRow struct {
	CabinID     string    `json:"cabin_id"`
	Ts          time.Time `json:"ts"`
	Temperature *float64  `json:"temperature"`
	Humidity    *float64  `json:"humidity"`
	Tds         *float64  `json:"tds"`
	Ph          *float64  `json:"ph"`
	ShtOk       bool      `json:"sht_ok"`
	RtcOk       bool      `json:"rtc_ok"`
	TdsOk       bool      `json:"tds_ok"`
	PhOk        bool      `json:"ph_ok"`
}

func (q *Queries) GetLatestReading(ctx context.Context, cabinID string) (GetLatestReadingRow, error) {
	row := q.db.QueryRow(ctx, getLatestReading, cabinID)
	var i GetLatestReadingRow
	err := row.Scan(
		&i.CabinID,
		&i.Ts,
		&i.Temperature,
		&i.Humidity,
		&i.Tds,
		&i.Ph,
		&i.ShtOk,
		&i.RtcOk,
		&i.TdsOk,
		&i.PhOk,
	)
	return i, err
}

const getReadings = `-- name: GetReadings :many
SELECT cabin_id, ts, temperature, humidity, tds, ph, sht_ok, rtc_ok, tds_ok, ph_ok
FROM readings
WHERE cabin_id = $1 AND ts >= $2 AND ts <= $3
ORDER BY ts DESC
LIMIT $4
`

type GetReadingsParams struct {
	CabinID string    `json:"cabin_id"`
	Ts      time.Time `json:"ts"`
	Ts_2    time.Time `json:"ts_2"`
	Limit   int32     `json:"limit"`
}

type GetReadingsRow struct {
	CabinID     string    `json:"cabin_id"`
	Ts          time.Time `json:"ts"`
	Temperature *float64  `json:"temperature"`
	Humidity    *float64  `json:"humidity"`
	Tds         *float64  `json:"tds"`
	Ph          *float64  `json:"ph"`
	ShtOk       bool      `json:"sht_ok"`
	RtcOk       bool      `json:"rtc_ok"`
	TdsOk       bool      `json:"tds_ok"`
	PhOk        bool      `json:"ph_ok"`
}

func (q *Queries) GetReadings(ctx context.Context, arg GetReadingsParams) ([]GetReadingsRow, error) {
	rows, err := q.db.Query(ctx, getReadings,
		arg.CabinID,
		arg.Ts,
		arg.Ts_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReadingsRow
	for rows.Next() {
		var i GetReadingsRow
		if err := rows.Scan(
			&i.CabinID,
			&i.Ts,
			&i.Temperature,
			&i.Humidity,
			&i.Tds,
			&i.Ph,
			&i.ShtOk,
			&i.RtcOk,
			&i.TdsOk,
			&i.PhOk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReadingsHourly = `-- name: GetReadingsHourly :many
SELECT date_trunc('hour', ts)::timestamptz AS bucket,
       AVG(temperature)::float8 AS temperature,
       AVG(humidity)::float8    AS humidity,
       AVG(tds)::float8         AS tds,
       AVG(ph)::float8          AS ph,
       COUNT(*)::bigint         AS samples
FROM readings
WHERE cabin_id = $1 AND ts >= $2 AND ts <= $3
GROUP BY bucket
ORDER BY bucket DESC
LIMIT $4
`

type GetReadingsHourlyParams struct {
	CabinID string    `json:"cabin_id"`
	Ts      time.Time `json:"ts"`
	Ts_2    time.Time `json:"ts_2"`
	Limit   int32     `json:"limit"`
}

type GetReadingsHourlyRow struct {
	Bucket      time.Time `json:"bucket"`
	Temperature float64   `json:"temperature"`
	Humidity    float64   `json:"humidity"`
	Tds         float64   `json:"tds"`
	Ph          float64   `json:"ph"`
	Samples     int64     `json:"samples"`
}

func (q *Queries) GetReadingsHourly(ctx context.Context, arg GetReadingsHourlyParams) ([]GetReadingsHourlyRow, error) {
	rows, err := q.db.Query(ctx, getReadingsHourly,
		arg.CabinID,
		arg.Ts,
		arg.Ts_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReadingsHourlyRow
	for rows.Next() {
		var i GetReadingsHourlyRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Temperature,
			&i.Humidity,
			&i.Tds,
			&i.Ph,
			&i.Samples,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAlert = `-- name: InsertAlert :exec
INSERT INTO alerts (cabin_id, ts, type, message)
VALUES ($1, $2, $3, $4)
`

type InsertAlertParams struct {
	CabinID string    `json:"cabin_id"`
	Ts      time.Time `json:"ts"`
	Type    string    `json:"type"`
	Message string    `json:"message"`
}

func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) error {
	_, err := q.db.Exec(ctx, insertAlert,
		arg.CabinID,
		arg.Ts,
		arg.Type,
		arg.Message,
	)
	return err
}

const insertReading = `-- name: InsertReading :exec
INSERT INTO readings (cabin_id, ts, temperature, humidity, tds, ph, sht_ok, rtc_ok, tds_ok, ph_ok)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertReadingParams struct {
	CabinID     string    `json:"cabin_id"`
	Ts          time.Time `json:"ts"`
	Temperature *float64  `json:"temperature"`
	Humidity    *float64  `json:"humidity"`
	Tds         *float64  `json:"tds"`
	Ph          *float64  `json:"ph"`
	ShtOk       bool      `json:"sht_ok"`
	RtcOk       bool      `json:"rtc_ok"`
	TdsOk       bool      `json:"tds_ok"`
	PhOk        bool      `json:"ph_ok"`
}

func (q *Queries) InsertReading(ctx context.Context, arg InsertReadingParams) error {
	_, err := q.db.Exec(ctx, insertReading,
		arg.CabinID,
		arg.Ts,
		arg.Temperature,
		arg.Humidity,
		arg.Tds,
		arg.Ph,
		arg.ShtOk,
		arg.RtcOk,
		arg.TdsOk,
		arg.PhOk,
	)
	return err
}

const markCabinOffline = `-- name: MarkCabinOffline :exec
UPDATE cabins SET online = false WHERE id = $1
`

func (q *Queries) MarkCabinOffline(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markCabinOffline, id)
	return err
}

const markCabinOnline = `-- name: MarkCabinOnline :exec
UPDATE cabins SET online = true, last_seen = $2 WHERE id = $1
`

type MarkCabinOnlineParams struct {
	ID       string     `json:"id"`
	LastSeen *time.Time `json:"last_seen"`
}

func (q *Queries) MarkCabinOnline(ctx context.Context, arg MarkCabinOnlineParams) error {
	_, err := q.db.Exec(ctx, markCabinOnline, arg.ID, arg.LastSeen)
	return err
}

const upsertActuatorState = `-- name: UpsertActuatorState :exec
INSERT INTO actuator_state (cabin_id, actuator, state, speed, source, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (cabin_id, actuator)
DO UPDATE SET state = EXCLUDED.state,
              speed = EXCLUDED.speed,
              source = EXCLUDED.source,
              updated_at = now()
`

type UpsertActuatorStateParams struct {
	CabinID  string `json:"cabin_id"`
	Actuator string `json:"actuator"`
	State    bool   `json:"state"`
	Speed    int32  `json:"speed"`
	Source   string `json:"source"`
}

func (q *Queries) UpsertActuatorState(ctx context.Context, arg UpsertActuatorStateParams) error {
	_, err := q.db.Exec(ctx, upsertActuatorState,
		arg.CabinID,
		arg.Actuator,
		arg.State,
		arg.Speed,
		arg.Source,
	)
	return err
}
